/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package stopwatch;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.TimeZone;

/**
 *
 * @author shintaro
 */
public class StopWatch extends javax.swing.JFrame {
    
    State currentState;
    State standBy;
    State measuring;
    State stopping;
    
    long passedTime;
    long startTime;
    
    SimpleDateFormat displayFormat =
            new SimpleDateFormat("HH:mm:ss.SSS");

    private abstract class State{
        public abstract void stopStart();
        public abstract void reset();
    }
    
    private class StandBy extends State{
        
        @Override
        public void stopStart() {
            currentState = measuring;
            startTime = new Date().getTime();
            display.setText("Measuring...");
        }

        @Override
        public void reset() { 
            //Nothing to do.
        }
        
    }
    
    private class Measuring extends State{

        @Override
        public void stopStart() {
            passedTime += new Date().getTime() - startTime;
            display.setText(
                    displayFormat.format(passedTime)
                    );
            currentState = stopping;
        }

        @Override
        public void reset() {
            //Nothing to do.
        }
        
    }
    
    private class Stopping extends State{

        @Override
        public void stopStart() {
            currentState = measuring;
            startTime = new Date().getTime();
            display.setText("Measuring...");
        }

        @Override
        public void reset() {
            passedTime = 0;            
            display.setText(
                displayFormat.format(
                    new Date(passedTime)
                )
        );
        }
        
    }
    
    
    /**
     * Creates new form StopWatch
     */
    public StopWatch() {
        initComponents();
        this.standBy = new StandBy();
        this.measuring = new Measuring();
        this.stopping = new Stopping();
        this.currentState = this.standBy;
        this.displayFormat.setTimeZone(TimeZone.getTimeZone("GMT"));
        this.display.setText(
                displayFormat.format(
                    new Date(this.passedTime)
                )
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        display = new javax.swing.JLabel();
        resetButton = new javax.swing.JButton();
        stopStartButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        display.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        display.setText("jLabel1");

        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        stopStartButton.setText("Start / Stop");
        stopStartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopStartButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(150, 150, 150)
                .add(display, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 98, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .add(layout.createSequentialGroup()
                .add(63, 63, 63)
                .add(resetButton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 77, Short.MAX_VALUE)
                .add(stopStartButton)
                .add(66, 66, 66))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(67, 67, 67)
                .add(display, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(83, 83, 83)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(resetButton)
                    .add(stopStartButton))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        this.currentState.reset();
    }//GEN-LAST:event_resetButtonActionPerformed

    private void stopStartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopStartButtonActionPerformed
        this.currentState.stopStart();
    }//GEN-LAST:event_stopStartButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StopWatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StopWatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StopWatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StopWatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new StopWatch().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel display;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton stopStartButton;
    // End of variables declaration//GEN-END:variables
}
