/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.*;
import javax.swing.event.TreeSelectionEvent;
import javax.swing.event.TreeSelectionListener;
import storage.*;

/**
 *
 * @author shintaro
 */
public class Frame extends javax.swing.JFrame {

    Navigator navigator;
    MainPanel mainPanel;

    class DisplayData implements Visitor {

        @Override
        public void visit(Volume volume) {
            Frame.this.mainPanel.removeAll();

            String[][] tableData = {
                {"Name", volume.getName()},
                {"Capacity(Bytes)", String.valueOf(volume.getCapacity())},
                {"Usage rate(%)", String.valueOf(volume.getUsedrate())}
            };

            Frame.this.mainPanel.add(new JTable(tableData, tableData[0]));
            Frame.this.mainPanel.validate();
            Frame.this.mainPanel.repaint();

        }

        @Override
        public void visit(DiskArray diskArray) {
            Frame.this.mainPanel.removeAll();
            String[][] tableData = {
                {"Name", diskArray.getName()},
                {"IP Address", String.valueOf(diskArray.getIpAddress())},};
            JTable table = new JTable(tableData, tableData[0]);
            Frame.this.mainPanel.add(table);
            Frame.this.validate();
            Frame.this.repaint();
        }
    }

    /**
     * Creates new form Frame
     */
    public Frame(Navigator navigator, MainPanel mainPanel) {
        initComponents();
        this.navigator = navigator;
        this.mainPanel = mainPanel;
        BoxLayout boxLayout = new BoxLayout(this.mainPanel, BoxLayout.PAGE_AXIS);
        this.mainPanel.setLayout(boxLayout);
        jSplitPane1.setLeftComponent(navigator);
        jSplitPane1.setRightComponent(mainPanel);
        JTree jTree = navigator.getJTree();


        jTree.addTreeSelectionListener(new TreeSelectionListener() {

            @Override
            public void valueChanged(TreeSelectionEvent tse) {
                Visitor visitor = new DisplayData();
                ((Element) tse.getPath().getLastPathComponent()).accept(visitor);
            }
        });


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setDividerLocation(200);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jSplitPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jSplitPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {


        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                Environment env = new Environment();
                DiskArray diskArray01 = new DiskArray();
                diskArray01.setVolumes(new ArrayList<Volume>());
                diskArray01.setEnvironment(env);
                DiskArray diskArray02 = new DiskArray();
                diskArray02.setVolumes(new ArrayList<Volume>());
                diskArray02.setEnvironment(env);

                env.setDiskArrays(new ArrayList<DiskArray>());
                env.getDiskArrays().add(diskArray01);
                env.getDiskArrays().add(diskArray02);

                Volume vol01 = new Volume();
                vol01.setName("vol01");
                vol01.setCapacity(10000000000L);
                vol01.setUsedrate(80.0);
                vol01.setDiskArray(diskArray01);
                Volume vol02 = new Volume();
                vol02.setName("vol02");
                vol02.setCapacity(20000000000L);
                vol02.setUsedrate(50.0);
                vol02.setDiskArray(diskArray01);

                diskArray01.getVolumes().add(vol01);
                diskArray01.getVolumes().add(vol02);
                diskArray01.setName("ETERNUS 410");
                diskArray01.setIpAddress("xx.xx.xx.xx");


                Volume vol03 = new Volume();
                vol03.setName("vol01");
                vol03.setCapacity(10000000000L);
                vol03.setUsedrate(80.0);
                vol03.setDiskArray(diskArray01);
                Volume vol04 = new Volume();
                vol04.setName("vol02");
                vol04.setCapacity(20000000000L);
                vol04.setUsedrate(50.0);
                vol04.setDiskArray(diskArray01);

                diskArray02.getVolumes().add(vol03);
                diskArray02.getVolumes().add(vol04);
                diskArray02.setName("ETERNUS 440");
                diskArray02.setIpAddress("yy.yy.yy.yy");

                Navigator navigator = new Navigator(env);
                MainPanel mainPanel = new MainPanel();

                new Frame(navigator, mainPanel).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
